### ISSUE TITLE
triggering another menu to open should close the previously opened menu

### ISSUE THREAD

**Issue by knomedia** [instructure-react/react-menu#6]
Steps to reproduce:

* Have two or more menus showing
* Open one of the menus
* Click something else on the page
  * Menu should close
* Open one of the menus
* Click the trigger of the second menu
  * previous menu should close, but stays open

See [lib/components/Menu.js](https://github.com/instructure-react/react-menu/blob/master/lib/components/Menu.js#L56). Code is only checking that the newly focused item has a `Menu__` className. In this case the second menu also has the appropriate className. As such the first menu, although it looses focus, stays open.

**Comment by tedlin182** [comment]
So I was comparing the various Menu components in Github vs what's in the NPM module and it looks like they're not consistent with each other. I wanted to ask if the NPM module is up to date or which I should use. I'm mainly interested in the changes for closing the open menu - https://github.com/instructure-react/react-menu/pull/7

So far all the changes in that PR are not present in the NPM module I just re-installed.

**Comment by knomedia** [comment]
i'll cut a new release once i get the build sorted it. it went a little wonky in a PR

**Comment by tedlin182** [comment]
Cool beans. Thanks and yeah let me know when that's up!

**Comment by tedlin182** [comment]
@knomedia Oh do you have a time estimate on when you think everything will be ready to update on the NPM side? We wanted it for our production release coming up pretty soon

**Comment by knomedia** [comment]
fixed by by https://github.com/instructure-react/react-menu/pull/7

**Comment by knomedia** [comment]
@tedlin182 0.0.6 with ^^ fix has been pushed to npm

**Comment by tedlin182** [comment]
Hey @knomedia - I tried updating/removing and re-installing/etc. and still am only getting the 0.0.5 version from NPM. Is there something I'm missing or is there possibly some issue still?

**Comment by knomedia** [comment]
@tedlin182 v0.0.6 is up on npm. I get the new version on a fresh `npm init` followed by `npm install --save react-menu`

have you bumped the version in your package.json file?

**Comment by tedlin182** [comment]
@knomedia 

Hey, yeah i bumped up the version and thought maybe just removing the module and re-doing `npm install --save react-menu` would have worked, but it didn't. I even just removed it from my package.json file completely and doing a `npm install --save react-menu` would work, but it didn't. 

Could be something with my local, but I'll try what you stated above and see if that works. If I run into the issue when we push the change to staging, I'll let you know.

**Comment by tedlin182** [comment]
@knomedia 

I actually just tried removing all of my node modules and running `npm install` and got this error:
```
No compatible version found: react-menu@'=0.0.6'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.5"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by knomedia** [comment]
@tedlin182 have you considered the nuclear option? `rm -rf node_modules && npm cache clean && npm install`

**Comment by tedlin182** [comment]
Still getting that error. I may check with the other devs to see if they're running into this issue, but it's quite odd it's not working.

```
npm ERR! notarget No compatible version found: react-menu@'>=0.0.6 <0.0.7'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.5"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by tedlin182** [comment]
@knomedia 

So there may have been some fix to React Menu that we did locally and pushed to our private NPM which may be causing the issue. Going to see if that's the cause though.

**Comment by tedlin182** [comment]
@knomedia 

I saw that you have the `/** @jsx React.DOM */` pragma still, but looks like that's been deprecated in the newer React versions 0.12:

https://github.com/callemall/material-ui/issues/364
https://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html

It was breaking on my local when starting up, but changing your file extensions to `.jsx` seemed to work.

Just a heads up
